/**
 * SQL Writer Module
 * Generates SQL INSERT dump statements in memory-safe chunks.
 */
import { MemoryManager } from "../../core/memory-manager.js";
import { IntegrityValidator } from "../../core/integrity-validator.js";
import { OutputManager } from "../../core/output-manager.js";
import { CONFIG } from "../../config/config.js";
import { sanitizeFileName } from "../../utils/file-utils.js";

export class SQLWriter {
    static async write(data, targetFormat, baseName, onProgress) {
        const { headers, rows, totalRows, totalColumns } = data;

        const validator = new IntegrityValidator();
        validator.setInputRecords(totalRows);

        const tableName = sanitizeFileName(baseName).replace(/\s+/g, "_").toLowerCase() || "converted_table";
        const cleanCols = headers.map(h => "`" + String(h).replace(/[`\\]/g, "") + "`").join(", ");

        const chunkSize = MemoryManager.getAdaptiveChunkSize(totalRows * 50);
        const sqlParts = [`-- SQL Insert Dump for '${tableName}'\n-- Generated by Personal File Converter\n\n`];
        let totalWritten = 0;

        for (let i = 0; i < totalRows; i += chunkSize) {
            const end = Math.min(i + chunkSize, totalRows);
            const valueTuples = [];

            for (let r = i; r < end; r++) {
                const row = rows[r];
                const vals = row.map(v => this.escapeSqlValue(v)).join(", ");
                valueTuples.push(`  (${vals})`);
            }

            const stmt = `INSERT INTO \`${tableName}\` (${cleanCols}) VALUES\n` + valueTuples.join(",\n") + ";\n\n";
            sqlParts.push(stmt);

            const count = end - i;
            totalWritten += count;

            validator.addCheckpoint({
                chunkIndex: Math.floor(i / chunkSize),
                startRecord: i,
                endRecord: end,
                expectedRecords: count,
                processedRecords: count,
                writtenRecords: count
            });

            valueTuples.length = 0;
            const progressPct = 30 + Math.round((end / totalRows) * 60);
            onProgress(progressPct, `Building SQL INSERT statements (${end.toLocaleString()} / ${totalRows.toLocaleString()})...`);
        }

        const validation = validator.validate();
        if (!validation.isValid) {
            throw new Error(validation.error.reason);
        }

        onProgress(95, "Creating final SQL Blob...");
        const blob = new Blob(sqlParts, { type: CONFIG.MIME_TYPES.sql });
        sqlParts.length = 0;

        onProgress(100, "Conversion to SQL completed successfully.");
        return OutputManager.createSingleFileResult(blob, `${baseName}.sql`, {
            totalRows,
            writtenRows: totalWritten,
            totalColumns
        });
    }

    static escapeSqlValue(val) {
        if (val === null || val === undefined || val === "") return "NULL";
        if (typeof val === "number") return val;
        if (typeof val === "boolean") return val ? 1 : 0;
        return `'${String(val).replace(/'/g, "''")}'`;
    }
}
